// src/routes/about/+page.svelte
<h2 class="text-center text-4xl font-bold tracking-tight">Bio.</h2>
<div
  class="prose mx-auto flex max-w-2xl flex-col text-justify leading-6 dark:prose-invert"
>
  <p class="mt-6">
    I&apos;m Joey. I&apos;ve got a passion for the web and developing services
    and applications with performance in mind. I&apos;ve spent nearly a decade
    working on technologies across the stack, from Java, IBM, .NET, and most of
    the major web frontend frameworks you&apos;ll see folks arguing about over
    on{' '}
    <a
      class="text-indigo-400 hover:text-indigo-500"
      href="https://reddit.com/r/webdev"
    >
      r/webdev
    </a>
    .
  </p>
  <p>
    By day, I&apos;m a Senior Software Engineer working on mostly .NET
    technologies in the web space. I&apos;ve worked professionally as a
    developer in healthcare, insurance, SaaS startups, manufacturing, and now
    finance. I enjoy building fast and efficient web services, exploring new
    technologies, and arguing with other developers about the value of
    pre-commit hooks when used wisely.{' '}
  </p>
  <p>
    In my spare time, I work primarily within the TypeScript and Rust ecosystems
    (I&apos;m even writing a{' '}
    <a
      class="text-indigo-400 hover:text-indigo-500"
      href="https://fullstackrust.netlify.app/"
    >
      Rust web series!
    </a>
    ), contributing to projects I find interesting and exploring new frontiers. I
    like to write about things I come across in the wild (of software), design, frameworks,
    and language features among other things. If I find the time, you can catch any
    of my content on{' '}
    <a
      class="text-indigo-400 hover:text-indigo-500"
      href="https://www.youtube.com/channel/UCkdpN-mQSyJ_2XJMU1kQ5fA#"
    >
      YouTube
    </a>{' '}
    or streaming live on{' '}
    <a
      class="text-indigo-400 hover:text-indigo-500"
      href="https://twitch.tv/JoeTheDevMan"
    >
      Twitch
    </a>
    . Checkout my{' '}
    <a class="text-indigo-400 hover:text-indigo-500" href="/blog">
      blog
    </a>{' '}
    for things I publish that mostly deal with my questionable takes on development.
  </p>
  <p>
    Outside of refactoring legacy code and convincing managers that estimates
    are not deadlines, I enjoy spending time with my wife and dog, family and
    friends, and sampling the latest installment of adult beverages at my local
    breweries.
  </p>
</div>

// src/app/about/page.tsx
export default function About() {
  return (
    <>
      <h2 className="text-center text-4xl font-bold tracking-tight">Bio.</h2>
      <div className="prose mx-auto flex max-w-2xl flex-col text-justify dark:prose-invert">
        <p className="mt-6">
          I&apos;m Joey. I&apos;ve got a passion for the web and developing
          services and applications with performance in mind. I&apos;ve spent
          nearly a decade working on technologies across the stack, from Java,
          IBM, .NET, and most of the major web frontend frameworks you&apos;ll
          see folks arguing about over on{' '}
          <a
            className="text-indigo-400 hover:text-indigo-500"
            href="https://reddit.com/r/webdev"
          >
            r/webdev
          </a>
          .
        </p>
        <p>
          By day, I&apos;m a Senior Software Engineer working on mostly .NET
          technologies in the web space. I&apos;ve worked professionally as a
          developer in healthcare, insurance, SaaS startups, manufacturing, and
          now finance. I enjoy building fast and efficient web services,
          exploring new technologies, and arguing with other developers about
          the value of pre-commit hooks when used wisely.{' '}
        </p>
        <p>
          In my spare time, I work primarily within the TypeScript and Rust
          ecosystems (I&apos;m even writing a{' '}
          <a
            className="text-indigo-400 hover:text-indigo-500"
            href="https://fullstackrust.netlify.app/"
          >
            Rust web series!
          </a>
          ), contributing to projects I find interesting and exploring new
          frontiers. I like to write about things I come across in the wild (of
          software), design, frameworks, and language features among other
          things. If I find the time, you can catch any of my content on{' '}
          <a
            className="text-indigo-400 hover:text-indigo-500"
            href="https://www.youtube.com/channel/UCkdpN-mQSyJ_2XJMU1kQ5fA#"
          >
            YouTube
          </a>
          or streaming live on
          <a
            className="text-indigo-400 hover:text-indigo-500"
            href="https://twitch.tv/JoeTheDevMan"
          >
            Twitch
          </a>
          . Checkout my
          <a href="/blog" className="text-indigo-400 hover:text-indigo-500">
            blog
          </a>
          for things I publish that mostly deal with my questionable takes on
          development.
        </p>
        <p>
          Outside of refactoring legacy code and convincing managers that
          estimates are not deadlines, I enjoy spending time with my wife and
          dog, family and friends, and sampling the latest installment of adult
          beverages at my local breweries.
        </p>
      </div>
    </>
  );
}
