// resources/js/Components/Footer.tsx
import * as React from 'react';
import PoweredBy from '@/Components/PoweredBy';

export default function Footer(): React.JSX.Element {
    return (
        <div className="max-w-screen-4xl mx-auto mt-auto flex w-full flex-col items-center justify-evenly gap-y-8 p-12 sm:flex-row sm:items-end">
            {/* <SocialIcons />
        <SpotifyNowPlaying>
            <Icon class="h-6 w-6" icon="logos:spotify-icon" />
        </SpotifyNowPlaying> */}
            <PoweredBy />
        </div>
    );
}

// components/Footer.vue
<template>
  <footer class="mx-auto max-w-7xl py-12 md:flex md:items-center md:justify-between">
    <div class="flex items-center justify-center space-x-6 md:order-1">
      <SpotifyNowPlaying>
        <UIcon name="i-logos-spotify-icon" class="size-6" />
      </SpotifyNowPlaying>
    </div>
    <div class="mt-8 md:order-2 md:mt-0">
      <PoweredBy />
    </div>
  </footer>
</template>
