// src/components/Header.tsx
import { RxCode } from 'react-icons/rx';

type HeaderProps = {
  title: string;
};

export default function Header({ title }: HeaderProps): JSX.Element {
  return (
    <span className="inline-flex flex-row items-center space-x-2 text-neutral-400">
      <RxCode className="h-8 w-8 sm:h-10 sm:w-10" />
      <h2 className="font-merriweather text-3xl font-bold tracking-tight sm:text-4xl">
        {title}
      </h2>
    </span>
  );
}

// components/Header.vue
<script setup lang="ts">
const props = defineProps<{ title: string }>();
</script>

<template>
  <span
    class="flex flex-row items-center space-x-0 text-neutral-400 sm:justify-center sm:space-x-2"
  >
    <HtmlTag additionalClasses="hidden sm:block text-xl" tagName="page">
      <h2
        class="font-mono text-2xl font-semibold tracking-tight text-neutral-400 sm:text-3xl"
      >
        {{ props.title }}
      </h2>
    </HtmlTag>
  </span>
</template>
