// resources/js/Components/BlogPreviews.tsx
import * as React from 'react';
import BlogCard from '@/Components/BlogCard';
import { type FrontMatter } from '@/models';

export default function BlogPreviews({
    frontMatters,
}: {
    frontMatters: FrontMatter[];
}): React.JSX.Element {
    return (
        <div className="mx-auto grid max-w-3xl grid-cols-1 gap-x-4 gap-y-12 py-8 sm:grid-cols-3">
            {frontMatters.map((frontMatter) => (
                <BlogCard key={frontMatter.title} frontMatter={frontMatter} />
            ))}
        </div>
    );
}

// resources/js/Components/BlogPreviews.vue
<script lang="ts" setup>
import { FrontMatter } from '@/models';
import BlogCard from '@/Components/BlogCard.vue';

defineProps<{ frontMatters: FrontMatter[] }>();
</script>

<template>
    <div
        class="mx-auto grid max-w-3xl grid-cols-1 gap-x-4 gap-y-12 py-8 sm:grid-cols-3"
    >
        <BlogCard
            v-for="frontMatter in frontMatters"
            :key="frontMatter.title"
            :front-matter="frontMatter"
        />
    </div>
</template>

<style scoped></style>
