// resources/js/Components/Navbar.tsx
import * as React from 'react';
import { Button } from '@/Components/ui/button';
import { Link } from '@inertiajs/react';
import { ThemeToggle } from '@/Components/ThemeToggle';

type NavLinkProps = {
    name: string;
    display: string;
};

const links: NavLinkProps[] = [
    {
        display: 'Home',
        name: 'home',
    },
    {
        display: 'About',
        name: 'about',
    },
    {
        display: 'Now',
        name: 'now',
    },
    {
        display: 'Blog',
        name: 'blogs',
    },
];

export function Navbar(): React.JSX.Element {
    return (
        <header>
            <nav className="flex flex-row items-center justify-center gap-x-2 px-6 py-8">
                {links.map(({ display, name }) => (
                    <Link
                        v-for="{ display, name } of links"
                        key={name}
                        href={route(name)}
                    >
                        <Button variant="outline">{display}</Button>
                    </Link>
                ))}
                <ThemeToggle />
            </nav>
        </header>
    );
}

// resources/js/Components/Navbar.vue
<script lang="ts" setup>
import { Button } from '@/Components/ui/button';
import { Link } from '@inertiajs/vue3';
import ThemeToggle from '@/Components/ThemeToggle.vue';

const links = [
    {
        to: 'home',
        display: 'Home',
    },
    {
        to: 'home',
        display: 'Now',
    },
    {
        to: 'blogs',
        display: 'Blog',
    },
];
</script>

<template>
    <nav class="flex flex-row items-center justify-center gap-x-2 px-6 pt-8">
        <Button v-for="link in links" :key="link.to" variant="outline">
            <Link :href="route(link.to)"> {{ link.display }}</Link>
        </Button>
        <ThemeToggle />
    </nav>
</template>

<style scoped></style>
