// src/components/navbar.tsx
import Link from "next/link";
import * as React from "react";
import { ThemeToggle } from "./theme-toggle";
import { Button } from "./ui/button";

type NavLinkProps = {
	href: string;
	display: string;
};

export const links: NavLinkProps[] = [
	{
		display: "Home",
		href: "/",
	},
	{
		display: "Now",
		href: "/now",
	},
	{
		display: "Blog",
		href: "/blogs",
	},
];

export function Navbar(): React.JSX.Element {
	return (
		<header>
			<nav className="flex flex-row items-center justify-center gap-x-2 px-6 py-8">
				<div className="space-x-2">
					{links.map(({ display, href }) => (
						<Link key={display} href={href}>
							<Button variant="outline">{display}</Button>
						</Link>
					))}
				</div>
				<ThemeToggle />
			</nav>
		</header>
	);
}

// resources/js/Components/Navbar.vue
<script lang="ts" setup>
import { Button } from '@/Components/ui/button';
import { Link } from '@inertiajs/vue3';
import ThemeToggle from '@/Components/ThemeToggle.vue';

const links = [
    {
        to: 'home',
        display: 'Home',
    },
    {
        to: 'home',
        display: 'Now',
    },
    {
        to: 'blogs',
        display: 'Blog',
    },
];
</script>

<template>
    <nav class="flex flex-row items-center justify-center gap-x-2 px-6 pt-8">
        <Button v-for="link in links" :key="link.to" variant="outline">
            <Link :href="route(link.to)"> {{ link.display }}</Link>
        </Button>
        <ThemeToggle />
    </nav>
</template>

<style scoped></style>
