// src/lib/components/Navbar.svelte
<script lang="ts">
  import { buttonVariants } from '$lib/components/ui/button';
  import ThemeToggle from '$lib/components/ThemeToggle.svelte';

  type NavLinkProps = {
    href: string;
    display: string;
  };

  const links: NavLinkProps[] = [
    {
      display: 'Home',
      href: '/',
    },
    {
      display: 'About',
      href: '/about',
    },
    {
      display: 'Blog',
      href: '/blog',
    },
  ];
</script>

<header>
  <nav class="flex flex-row items-center justify-center gap-x-2 px-6 py-8">
    {#each links as { display, href }}
      <a class={buttonVariants({ variant: 'outline' })} {href}>
        {display}
      </a>
    {/each}
    <ThemeToggle />
  </nav>
</header>

// resources/js/Components/Navbar.tsx
import * as React from 'react';
import { Button } from '@/Components/ui/button';
import { Link } from '@inertiajs/react';
import { ThemeToggle } from '@/Components/ThemeToggle';

type NavLinkProps = {
    name: string;
    display: string;
};

const links: NavLinkProps[] = [
    {
        display: 'Home',
        name: 'home',
    },
    {
        display: 'About',
        name: 'about',
    },
    {
        display: 'Blog',
        name: 'blogs',
    },
];

export function Navbar(): React.JSX.Element {
    return (
        <header>
            <nav className="flex flex-row items-center justify-center gap-x-2 px-6 py-8">
                {links.map(({ display, name }) => (
                    <Link
                        v-for="{ display, name } of links"
                        key={name}
                        href={route(name)}
                    >
                        <Button variant="outline">{display}</Button>
                    </Link>
                ))}
                <ThemeToggle />
            </nav>
        </header>
    );
}
