// src/lib/components/PoweredBy.svelte
<script lang="ts">
  import Icon from '@iconify/svelte';

  export let commitSha = '';
  const commitShaForDisplay = commitSha.substring(0, 6);
  const commitUrl = `https://github.com/JoeyMckenzie/joey-mckenzie-tech/commit/${commitSha}`;
  const poweredBy = [
    {
      display: 'Svelte',
      href: 'https://svelte.dev',
      icon: 'logos:svelte-icon',
    },
    {
      display: 'Vercel',
      href: 'https://vercel.com',
      icon: 'simple-icons:vercel',
      classes: 'dark:text-white text-black',
    },
  ];
</script>

<div class="mx-auto inline-flex flex-row items-center gap-x-4 md:mx-0">
  <p class="font-ubuntu text-center text-xs leading-5">Powered by</p>
  {#each poweredBy as { display, icon, href, classes }}
    <a {href}>
      <span class="sr-only">{display}</span>
      <Icon
        class={`h-5 w-5 transition duration-300 ease-in-out hover:-translate-y-1 hover:scale-110 ${classes}`}
        {icon}
      />
    </a>
  {/each}
  <a class="font-ubuntu text-center text-xs leading-5" href={commitUrl}>
    {commitShaForDisplay}
  </a>
</div>

// resources/js/Components/PoweredBy.vue
<script lang="ts" setup>
import { Icon } from '@iconify/vue';
import { computed } from 'vue';

const props = defineProps<{
    commitSha: string;
}>();

const commitShaForDisplay = computed(() => props.commitSha.substring(0, 6));
const commitUrl = computed(
    () =>
        `https://github.com/JoeyMckenzie/joey-mckenzie-tech/commit/${props.commitSha}`,
);
const poweredBy = [
    {
        display: 'Larvel',
        href: 'https://laravel.com',
        icon: 'logos:laravel',
    },
    {
        display: 'Vue',
        href: 'https://vuejs.org',
        icon: 'logos:vue',
    },
    {
        display: 'Fly.io',
        href: 'https://fly.io',
        icon: 'logos:fly-icon',
    },
];
</script>

<template>
    <div class="mx-auto inline-flex flex-row items-center gap-x-4 md:mx-0">
        <p class="font-ubuntu text-center text-xs leading-5">Powered by</p>
        <a
            v-for="{ display, icon, href } in poweredBy"
            :key="icon"
            :href="href"
        >
            <span class="sr-only">{{ display }}</span>
            <Icon
                :icon="icon"
                class="h-5 w-5 transition duration-300 ease-in-out hover:-translate-y-1 hover:scale-110"
            />
        </a>
        <a
            :href="commitUrl"
            class="font-ubuntu text-center text-xs leading-5 hover:underline"
        >
            {{ commitShaForDisplay }}
        </a>
    </div>
</template>
