// resources/js/Pages/Blog/Post.vue
<script lang="ts" setup>
import MainLayout from '@/Layouts/MainLayout.vue';
import { Head, Link } from '@inertiajs/vue3';
import { Post } from '@/types';
import { computed } from 'vue';
import { Badge } from '@/Components/ui/badge';
import { Button } from '@/Components/ui/button';

const props = defineProps<{
    post: Post;
    keywords: string[];
}>();

const keywordList = computed(() => props.keywords.join(','));
const altText = computed(() => `${props.post.title} blog meme`);
</script>

<template>
    <Head>
        <meta :content="keywordList" name="keywords" />
        <title>
            {{ post.title }}
        </title>
    </Head>

    <MainLayout>
        <div class="flex flex-col justify-center pt-12">
            <article
                class="prose mx-auto w-full overflow-hidden pb-6 dark:prose-invert prose-pre:text-sm prose-img:mx-auto prose-img:rounded-md"
            >
                <h1 class="text-center text-2xl font-semibold">
                    {{ post.title }}
                </h1>
                <div
                    class="flex flex-row items-center justify-center gap-x-2 text-sm tracking-tight"
                >
                    <time dateTime="{post.pubDate}"
                        >{{ post.published_date }}
                    </time>
                    <Badge variant="secondary">{{ post.category }}</Badge>
                    <p>{{ post.views }} views</p>
                </div>
                <img
                    :alt="altText"
                    :src="post.hero_image"
                    height="400"
                    width="500"
                />
                <!-- eslint-disable-next-line vue/no-v-html -->
                <div v-html="post.parsed_content" />
            </article>
            <Link :href="route('blog')" class="mx-auto max-w-md">
                <Button variant="secondary"> Back to blogs</Button>
            </Link>
        </div>
    </MainLayout>
</template>

// resources/js/Pages/Blog/Post/Index.tsx
import { Badge } from "@/Components/ui/badge";
import { Button } from "@/Components/ui/button";
import MainLayout from "@/Layouts/MainLayout";
import { type Post } from "@/models";
import { Head, Link } from "@inertiajs/react";
import * as React from "react";

export default function BlogPost({ post }: { post: Post }): React.JSX.Element {
    const formattedDate = new Date(
        post.published_date ?? "",
    ).toLocaleDateString("en-us", {
        year: "numeric",
        month: "short",
        day: "numeric",
    });

    return (
        <>
            <Head title={`${post.title} | joeymckenzie.tech`}>
                <meta name="keywords" content={post.keywords} />
            </Head>

            <MainLayout>
                <div className="flex flex-col justify-center">
                    <article className="prose mx-auto w-full overflow-hidden pb-6 dark:prose-invert prose-pre:text-sm prose-img:mx-auto prose-img:rounded-md">
                        <h1 className="text-center text-2xl">{post.title}</h1>
                        <div className="flex flex-row items-center justify-center gap-x-2 text-sm tracking-tight">
                            <time dateTime={post.published_date}>
                                {formattedDate}
                            </time>
                            <Badge>{post.category}</Badge>
                            <p>{post.views} views</p>
                        </div>
                        <img
                            alt={`${post.title} blog meme`}
                            src={post.hero_image}
                            height="400"
                            width="500"
                        />
                        <div
                            // biome-ignore lint/security/noDangerouslySetInnerHtml: controlled input
                            dangerouslySetInnerHTML={{
                                __html: post.parsed_content,
                            }}
                        />
                    </article>
                    <Link href={route("blogs")} className="mx-auto max-w-md">
                        <Button variant="secondary"> Back to blogs</Button>
                    </Link>
                </div>
            </MainLayout>
        </>
    );
}
