// src/app/blog/[slug]/page.tsx
import { Button } from '@/components/ui/button';
import { allPosts } from 'contentlayer/generated';
import Link from 'next/link';

export const generateStaticParams = async () =>
  allPosts.map((post) => ({ slug: post._raw.flattenedPath }));

export const generateMetadata = ({ params }: { params: { slug: string } }) => {
  const post = allPosts.find((post) => post._raw.flattenedPath === params.slug);

  if (!post) {
    throw new Error(`Post not found for slug: ${params.slug}`);
  }

  return { title: post.title };
};

export default async function PostPage({
  params,
}: {
  params: { slug: string };
}) {
  const post = allPosts.find((post) => post._raw.flattenedPath === params.slug);

  if (!post) {
    throw new Error(`Post not found for slug: ${params.slug}`);
  }

  return (
    <>
      <article className="prose prose-invert mx-auto overflow-hidden pb-6 text-justify text-neutral-400 prose-h2:text-neutral-200 prose-a:text-neutral-200 hover:prose-a:text-neutral-300 prose-code:text-neutral-300 prose-img:mx-auto prose-img:rounded-md">
        <h1 className="text-center text-2xl text-neutral-300">{post.title}</h1>
        <div className="flex flex-row items-center justify-center gap-x-2 text-sm tracking-tight">
          <time
            dateTime={new Date(post.pubDate).toISOString()}
            className="text-neutral-400"
          >
            {new Date(post.pubDate).toLocaleDateString('en-us', {
              year: 'numeric',
              month: 'short',
              day: 'numeric',
            })}
          </time>
          <span className="font-bold">{post.category}</span>
        </div>
        {/* <Image
          width="540"
          height="280"
          src={post.heroImage}
          alt="Blog header image"
        /> */}
        <div
          dangerouslySetInnerHTML={{
            __html: post.body.html,
          }}
        />
      </article>
      <Button asChild>
        <Link href="/blog">Back to blogs</Link>
      </Button>
    </>
  );
}

// pages/blog/[...slug].vue
<script setup lang="ts">
const { path } = useRoute();

// Fire and forget, no need to block rendering
useFetch('/api/blogs/view', {
  method: 'POST',
  body: { slug: path.split('/')[2] ?? '' },
});
</script>

<template>
  <div>
    <ContentDoc v-slot="{ doc }">
      <article
        class="prose prose-invert mx-auto overflow-hidden pb-12 font-merriweather text-neutral-400 prose-h2:text-neutral-200 prose-a:text-neutral-200 hover:prose-a:text-neutral-300 prose-code:text-neutral-300 prose-img:mx-auto prose-img:rounded-md"
      >
        <h1 class="text-center font-merriweather text-2xl text-neutral-300">
          {{ doc.title }}
        </h1>
        <div
          class="flex flex-row items-center justify-center gap-x-2 font-roboto-mono text-sm tracking-tighter"
        >
          <FormattedDate :date="new Date(doc.pubDate)" />
          <span class="font-bold">#{{ doc.category }}</span>
        </div>
        <img
          width="540"
          height="280"
          :src="doc.heroImage"
          alt="Blog header image"
        />
        <ContentRenderer :value="doc" />
      </article>
      <NuxtLink
        to="/blog"
        type="button"
        class="mx-auto flex w-40 items-center justify-center gap-x-1.5 rounded-md bg-neutral-800 px-3 py-2 text-sm font-semibold text-neutral-400 shadow-sm hover:bg-neutral-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-neutral-600"
      >
        <Icon name="ic:round-arrow-back" class="h-6 w-6" />
        Back to blogs
      </NuxtLink>
    </ContentDoc>
  </div>
</template>
