// src/app/blog/[slug]/page.tsx
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { addViewCount } from '@/lib/db';
import { allPosts } from 'contentlayer/generated';
import Image from 'next/image';
import Link from 'next/link';

export const generateStaticParams = async () =>
  allPosts.map((post) => ({ slug: post._raw.flattenedPath }));

export const generateMetadata = ({ params }: { params: { slug: string } }) => {
  const post = allPosts.find((post) => post._raw.flattenedPath === params.slug);

  if (!post) {
    throw new Error(`Post not found for slug: ${params.slug}`);
  }

  return { title: post.title };
};

export default async function PostPage({
  params,
}: {
  params: { slug: string };
}) {
  const post = allPosts.find((post) => post._raw.flattenedPath === params.slug);

  if (!post) {
    throw new Error(`Post not found for slug: ${params.slug}`);
  }

  await addViewCount(params.slug);

  return (
    <div className="flex flex-col justify-center">
      <article className="prose mx-auto w-full overflow-hidden pb-6 dark:prose-invert prose-img:mx-auto prose-img:rounded-md">
        <h1 className="text-center text-2xl">{post.title}</h1>
        <div className="flex flex-row items-center justify-center gap-x-2 text-sm tracking-tight">
          <time dateTime={new Date(post.pubDate).toISOString()}>
            {new Date(post.pubDate).toLocaleDateString('en-us', {
              year: 'numeric',
              month: 'short',
              day: 'numeric',
            })}
          </time>
          <Badge>{post.category}</Badge>
        </div>
        <Image
          width="540"
          height="280"
          src={post.heroImage}
          alt="Blog header image"
        />
        <div
          dangerouslySetInnerHTML={{
            __html: post.body.html,
          }}
        />
      </article>
      <Button className="mx-auto max-w-md" asChild>
        <Link href="/blog">Back to blogs</Link>
      </Button>
    </div>
  );
}

// src/routes/blog/[slug]/+page.svelte
<script lang="ts">
  import type { PageServerData } from './$types';
  import { Badge } from '$lib/components/ui/badge';
  import { Button } from '$lib/components/ui/button';

  export let data: PageServerData;

  const content = data.post?.body?.html ?? '';
</script>

<svelte:head>
  <title>{data.post?.title} | joeymckenzie.tech</title>
</svelte:head>

<div class="flex flex-col justify-center">
  <article
    class="prose mx-auto w-full overflow-hidden pb-6 dark:prose-invert prose-img:mx-auto prose-img:rounded-md"
  >
    <h1 class="text-center text-2xl">{data.post?.title}</h1>
    <div
      class="flex flex-row items-center justify-center gap-x-2 text-sm tracking-tight"
    >
      <time dateTime={new Date(data.post?.pubDate ?? '')?.toISOString() ?? ''}>
        {new Date(data.post?.pubDate ?? '').toLocaleDateString('en-us', {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
        })}
      </time>
      <Badge>{data.post?.category}</Badge>
    </div>
    <img
      height="400"
      width="500"
      alt="Blog header"
      src={data.post?.heroImage}
    />
    <!-- eslint-disable-next-line  -->
    {@html content}
  </article>
  <Button class="mx-auto max-w-md">
    <a href="/blog">Back to blogs</a>
  </Button>
</div>
