// app/pages/blog/[slug].vue
<script setup lang="ts">
import type { Post } from '~~/types/content';

const route = useRoute();
const slug = computed(() => route.params.slug as string);
const { data } = await useFetch<{ post: Post; keywords: string[] }>(`/api/blog/${slug.value}`);
const post = computed(() => data.value?.post);
const keywords = computed(() => data.value?.keywords?.join(', ') ?? '');

if (!post.value) {
  await navigateTo('/blog');
}
</script>

<template>
  <main v-if="post" class="mx-auto py-12">
    <Head>
      <Meta name="description" :content="post.description" />
      <Meta name="keywords" :content="keywords" />
    </Head>
    <article class="prose dark:prose-invert mx-auto">
      <h1 class="text-2xl sm:text-center">
        {{ post!.title }}
      </h1>
      <div class="flex flex-row items-center justify-center gap-x-2 text-sm tracking-tighter">
        <FormattedDate :date="post!.pubDate" />
        <UBadge :label="post!.category" />
        <FormattedViews v-if="post?.views" :views="post.views" />
      </div>
      <NuxtImg
        :src="post!.heroImage" :alt="`${post!.title} blog meme image`"
        class="mx-auto rounded-md"
      />
      <div class="text-sm leading-6 dark:text-neutral-400" v-html="post?.content" />
    </article>
    <div class="flex justify-center pt-8">
      <UButton to="/blog">
        Back to blog
      </UButton>
    </div>
  </main>
</template>

// src/routes/blog/[slug]/+page.svelte
<script lang="ts">
  import { Badge } from '$lib/components/ui/badge';
  import { Button } from '$lib/components/ui/button';
  import type { PageServerData } from './$types';

  export let data: PageServerData;

  const markdownContent = data.post?.body?.html ?? '';
</script>

<svelte:head>
  <title>{data.post.title} | joeymckenzie.tech</title>
  <meta content={data.post.description} name="description" />
  {#if data.post.keywords && data.post.keywords.length > 0}
    <meta name="keywords" content={data.post.keywords.join(',')} />
  {/if}
</svelte:head>

<div class="flex flex-col justify-center">
  <article
    class="prose mx-auto w-full overflow-hidden pb-6 dark:prose-invert prose-img:mx-auto prose-img:rounded-md"
  >
    <h1 class="text-center text-2xl">{data.post.title}</h1>
    <div
      class="flex flex-row items-center justify-center gap-x-2 text-sm tracking-tight"
    >
      <time dateTime={new Date(data.post.pubDate ?? '')?.toISOString() ?? ''}>
        {new Date(data.post.pubDate ?? '').toLocaleDateString('en-us', {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
        })}
      </time>
      <Badge>{data.post.category}</Badge>
    </div>
    <img
      height="400"
      width="500"
      alt={`${data.post.title} hero image`}
      src={data.post.heroImage}
    />
    <!-- eslint-disable-next-line  -->
    {@html markdownContent}
  </article>
  <Button class="mx-auto max-w-md">
    <a href="/blog">Back to blogs</a>
  </Button>
</div>
