// src/components/blog/SilentViewCounts.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { ViewCountMetadata } from './view-counts';
  import { viewCountStore } from './view-counts';

  export let apiBaseUrl = '';
  export let includeTopCounts = false;

  async function getAllViewCounts(): Promise<ViewCountMetadata> {
    const viewCountResponse = await fetch(`${apiBaseUrl}/views`);
    return viewCountResponse.json();
  }

  async function getTopViewCounts(): Promise<ViewCountMetadata> {
    const viewCountResponse = await fetch(`${apiBaseUrl}/views/top`);
    return viewCountResponse.json();
  }

  onMount(async () => {
    const viewCounts = [getAllViewCounts()];

    if (includeTopCounts) {
      viewCounts.push(getTopViewCounts());
    }

    const { set } = viewCountStore;
    const [allViewCountsData, topViewCountsData] = await Promise.all(
      viewCounts
    );

    set({
      allBlogs: allViewCountsData,
      topBlogs: topViewCountsData,
    });
  });
</script>

// src/components/blog/SilentViewCounts.vue
<script setup lang="ts">
import { provide } from 'vue';

const props = defineProps<{
  apiBaseUrl: string;
  includeTopCounts: boolean;
}>();

export type ViewCountMeta = {
  count: number;
  slug: string;
};

export type ViewCountMetadata = {
  counts: ViewCountMeta[];
};

try {
  const url = props.includeTopCounts
    ? `${props.apiBaseUrl}/views/top`
    : `${props.apiBaseUrl}/views`;

  const viewCountsResponse = await fetch(url);
  const viewCounts: ViewCountMetadata = await viewCountsResponse.json();

  provide<ViewCountMetadata>('viewCounts', viewCounts);
} catch (e) {
  console.error(e);
}
</script>

<template>
  <div />
</template>
