// resources/js/Components/Footer.tsx
import * as React from 'react';
import PoweredBy from '@/Components/PoweredBy';

export default function Footer(): React.JSX.Element {
    return (
        <div className="max-w-screen-4xl mx-auto mt-auto flex w-full flex-col items-center justify-evenly gap-y-8 p-12 sm:flex-row sm:items-end">
            {/* <SocialIcons />
        <SpotifyNowPlaying>
            <Icon class="h-6 w-6" icon="logos:spotify-icon" />
        </SpotifyNowPlaying> */}
            <PoweredBy />
        </div>
    );
}

// src/lib/components/Footer.svelte
<script lang="ts">
  import PoweredBy from '$lib/components/PoweredBy.svelte';
  import SocialIcons from '$lib/components/SocialIcons.svelte';
  import SpotifyNowPlaying from '$lib/components/SpotifyNowPlaying.svelte';
  import type { NowPlayingResponse } from '$lib/spotify';
  import Icon from '@iconify/svelte';

  const { commitSha, nowPlaying } = $props<{
    commitSha: string;
    nowPlaying: NowPlayingResponse;
  }>();
</script>

<div
  class="mx-auto mt-auto flex w-full max-w-screen-lg flex-col items-center justify-evenly gap-y-8 p-12 sm:flex-row sm:items-end"
>
  <SocialIcons />
  <SpotifyNowPlaying {nowPlaying}>
    <Icon class="h-6 w-6" icon="logos:spotify-icon" />
  </SpotifyNowPlaying>
  <PoweredBy {commitSha} />
</div>
