// src/components/footer/spotify/SpotifyCurrentlyPlaying.vue
<script setup lang="ts">
import type { NowPlayingResponse } from './SpotifyNowPlaying.vue';

const props = defineProps<{ response: NowPlayingResponse }>();
</script>

<template>
  <a
    :href="props.response.href"
    target="_blank"
    rel="noreferrer"
    class="flex flex-col space-y-1"
  >
    <h2
      class="inline-flex justify-center font-ubuntu text-xs text-neutral-400 md:justify-start"
    >
      Now listening
    </h2>
    <div class="flex flex-row items-center justify-center space-x-2">
      <slot />
      <img
        :src="props.response.albumImageSrc"
        width="30"
        height="30"
        alt="Spotify listenting to"
        class="rounded-sm"
      />
      <div class="flex flex-col truncate">
        <h4 class="text-xs font-semibold text-neutral-300">
          {{ props.response.trackTitle }}
        </h4>
        <p class="text-xs text-neutral-400">{{ props.response.artist }}</p>
      </div>
    </div>
  </a>
</template>

// src/lib/components/SpotifyCurrentlyPlaying.svelte
<script lang="ts">
  import type { NowPlayingResponse } from '$lib/spotify';

  const { nowPlaying } = $props<{ nowPlaying: NowPlayingResponse }>();
</script>

<a
  class="flex flex-col space-y-1"
  href={nowPlaying.href}
  rel="noreferrer"
  target="_blank"
>
  <h2 class="font-ubuntu inline-flex justify-center text-xs">Now listening</h2>
  <div class="flex flex-row items-center justify-center space-x-2">
    <slot />
    <img
      alt="Spotify listenting to"
      class="rounded-sm"
      height="30"
      src={nowPlaying.albumImageSrc}
      width="30"
    />
    <div class="flex max-w-[16rem] flex-col">
      <h4
        class="line-clamp-1 overflow-hidden text-ellipsis text-xs font-semibold"
      >
        {nowPlaying.trackTitle}
      </h4>
      <p class="text-xs">{nowPlaying.artist}</p>
    </div>
  </div>
</a>
