// resources/js/Components/SpotifyNowPlaying.vue
<script lang="ts" setup>
import SpotifyCurrentlyPlaying from './SpotifyCurrentlyPlaying.vue';
import SpotifyNotPlaying from './SpotifyNotPlaying.vue';
import { usePage } from '@inertiajs/vue3';
import { computed } from 'vue';

const page = usePage();

const nowPlaying = computed(() => page.props.spotify);
const isPlaying = computed(() => nowPlaying.value?.nowPlaying);
</script>

<template>
    <SpotifyCurrentlyPlaying v-if="isPlaying" :now-playing="nowPlaying!">
        <slot />
    </SpotifyCurrentlyPlaying>
    <SpotifyNotPlaying v-else>
        <slot />
    </SpotifyNotPlaying>
</template>

// src/lib/components/SpotifyNowPlaying.svelte
<script lang="ts">
  import SpotifyCurrentlyPlaying from '$lib/components/SpotifyCurrentlyPlaying.svelte';
  import SpotifyNotPlaying from '$lib/components/SpotifyNotPlaying.svelte';
  import type { NowPlayingResponse } from '$lib/spotify';

  const { nowPlaying } = $props<{ nowPlaying: NowPlayingResponse }>();
</script>

{#if nowPlaying?.nowPlaying}
  <SpotifyCurrentlyPlaying {nowPlaying}>
    <slot />
  </SpotifyCurrentlyPlaying>
{:else}
  <SpotifyNotPlaying>
    <slot />
  </SpotifyNotPlaying>
{/if}
